theme: minima
title: NeuroHumanities
#author: 
#email: email goes here
description: University of Houston
permalink: pretty
header_pages:
  - about.md
  - research.md
  - people.md
  - lab.md
  - calendar.md
  - contact.md
show_excerpts: true
excerpt_separator: <!--more-->
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
paginate: 3
paginate_path: "/page-:num/"
